---
services:
  proxy:
    image: traefik:v2.10
    container_name: proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /run/docker.sock:/run/docker.sock
    networks:
      proxynet:

networks:
  proxynet:
