---
services:
  hello:
    image: ${HELLO_IMAGE_NAME}:${HELLO_IMAGE_TAG:-latest}
    container_name: hello
    environment:
      - PORT=${HELLO_PORT:-80}
    ports:
      - 8080:${HELLO_PORT:-80}
    volumes:
      - hellostatus:/var/lib/hello-http
    restart: always
    networks:
      hellonet:
        ipv4_address: ${HELLO_NET}.${HELLO_IPV4:?IP undefined}

networks:
  hellonet:
    ipam:
      config:
        - subnet: ${HELLO_NET}.0/24
          gateway: ${HELLO_NET}.254
    driver_opts:
      com.docker.network.bridge.name: hellonet0

volumes:
  hellostatus:
    name: autrenom
    external: true
