---
services:
  hello:
    image: bob2606/hello-http:0.8.15
    container_name: hello
    environment:
      - PORT=80
    ports:
      - 8080:80
    volumes:
      - hellostatus:/var/lib/hello-http
    restart: always
    networks:
      hellonet:
        ipv4_address: 172.88.0.100

networks:
  hellonet:
    ipam:
      config:
        - subnet: 172.88.0.0/16
          gateway: 172.88.0.254
    driver_opts:
      com.docker.network.bridge.name: hellonet0

volumes:
  hellostatus:
    external: true
