---
services:
  aww:
    image: ${NGINX_IMAGE_NAME}:${NGINX_IMAGE_TAG}
    container_name: www
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./site:/usr/share/nginx/html
    restart: always
    networks:
      lempnet:
        ipv4_address: 172.80.0.100

  php:
    image: ${PHP_IMAGE_NAME}:${PHP_IMAGE_TAG}
    build:
      context: .
    container_name: php
    volumes:
      - ./site:/var/www/html
    restart: always
    networks:
      lempnet:
        ipv4_address: 172.80.0.150

  db:
    image: ${MARIADB_IMAGE_NAME}:${MARIADB_IMAGE_TAG}
    container_name: db
    volumes:
      - datadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=stage
    restart: always
    networks:
      lempnet:
        ipv4_address: 172.80.0.200

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.80.0.0/16
          gateway: 172.80.0.1
    driver_opts:
      com.docker.network.bridge.name: lempnet0

volumes:
  datadb:
