---
services:
  aww:
    image: nginx:1.26
    container_name: www
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./site:/usr/share/nginx/html
    restart: always
    networks:
      lempnet:
        ipv4_address: 172.80.0.100

  php:
    image: php:8.3-fpm
    container_name: php
    volumes:
      - ./site:/var/www/html
    restart: always
    networks:
      lempnet:
        ipv4_address: 172.80.0.150

  db:
    image: mariadb:10.8
    container_name: db
    volumes:
      - datadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
      - MARIADB_DATABASE=stage
    restart: always
    networks:
      lempnet:
        ipv4_address: 172.80.0.200

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.80.0.0/16
          gateway: 172.80.0.1
    driver_opts:
      com.docker.network.bridge.name: lempnet0

volumes:
  datadb:
